//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCake
    {
        public int CakeId { get; set; }
        public string Name { get; set; }
        public bool IsForChildren { get; set; }
        public double PurchasePrice { get; set; }
        public double SellingPrice { get; set; }
    }
}
