//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrderDetail
    {
        public int ListOfCakeInOrderId { get; set; }
        public int OrderId { get; set; }
        public int CakeId { get; set; }
        public int Expr1 { get; set; }
        public System.DateTime Date { get; set; }
        public double TotalPrice { get; set; }
        public int NumberOfCakes { get; set; }
        public int Expr2 { get; set; }
        public int CustomerId { get; set; }
    }
}
