//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastryShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PastryShopEntities1 : DbContext
    {
        public PastryShopEntities1()
            : base("name=PastryShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cake> Cakes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ListOfCakeInOrder> ListOfCakeInOrders { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<vwCake> vwCakes { get; set; }
        public virtual DbSet<vwCustomer> vwCustomers { get; set; }
        public virtual DbSet<vwOrder> vwOrders { get; set; }
        public virtual DbSet<vwOrderDetail> vwOrderDetails { get; set; }
    }
}
